# Fazit  

Die Thesis schliesst mit einem Fazit. Dieses gliedert sich in eine Zusammenfassung der Arbeit. Darauf folgt eine Schlussfolgerung und ein Ausblick.

## Zusammenfassung  

Diese Thesis liefert einen Beitrag zur Beschreibung des nichtlinearen Tragverhaltens von Stahlbetontragwerken. Sie zeigt eine praxisnahe Methode auf, um das Tragverhalten von Stahlbetonbalken und -platten zu beschreiben. Dies erfolgt ausschliesslich mit der in der Praxis üblichen Statiksoftware AxisVM. Dazu ist eine Modellbildung beschrieben, welche starre Stäbe über Gelenke koppelt, in denen nichtlineare Gelenkbeziehungen hinterlegt sind. Im zweidimensionalen Raum lassen sich beliebige Stabtragwerke abbilden. Angeordnet als Trägerrost ermöglicht das NLFE-Modell die Abbildung des Tragverhaltens von Flächentragwerken.  

Der erste Teil der Arbeit, die Modellbildung, legt die Grundlagen des NLFE-Modells dar. Ein einleitendes Gedankenexperiment verdeutlicht das Modellverhalten an einem einfachen Balken. Darauf folgt das Berechnungsschema, welches das Modell in die Systemmodellbildung und die Querschnittsmodellbildung unterteilt. Die Systemmodellbildung umfasst die starren Stäbe, die Anordnung der Gelenke und die Berechnung der Resultate. Die Querschnittsmodellbildung ist einzeln für Balken- und Plattentragwerke beschrieben.  

Die Querschnittsmodellbildung der Balken zeigt die Ermittlung der nichtlinearen Biegesteifigkeit unter Berücksichtigung der Zugversteifung, basierend auf dem Zuggurtmodell.  

Die Querschnittsmodellbildung der Platten beschreibt das allgemeine Plattentragverhalten. Darauf folgt eine Transformation vom Plattenelement zum Trägerrost. Abschliessend zeigt sie das nichtlineare Biegetragverhalten des Plattenelements, bestehend aus dem Biege- und Drillverhalten.  

Der zweite Teil der Arbeit demonstriert die Anwendung der Modelle an Beispielen. Die Modellbildung der Balken ist an einem Zweifeldträger vollständig aufgezeigt. Der Zweifeldträger ist mit zwei unterschiedlich duktilen Betonstählen modelliert. Das Tragverhalten ist zunächst analytisch und anschliessend mit dem NLFE-Modell ermittelt. Die Resultate zeigen eine Übereinstimmung.  

Darauf folgt die Anwendung an einem torsionsweichen Trägerrost. Dieses Beispiel verifiziert die Anwendbarkeit des Modells im dreidimensionalen Raum. Die Traglast ist sowohl analytisch als auch mit dem NLFE-Modell ermittelt. Auch hier stimmen die Resultate überein.  

Die Quadratplatte demonstriert die Anwendung der Modellbildung für Platten. Auch hier ist die Traglast analytisch bestimmt und mit dem NLFE-Modell verglichen. Die Resultate stimmen wiederum überein.  

Den Abschluss bildet die Nachrechnung eines grossmassstäblichen Plattenexperiments. Die Zweifeldplatte wendet sämtliche Herleitungen aus dem ersten Teil der Arbeit an. Der Vergleich der Messresultate mit dem prognostizierten Tragverhalten des NLFE-Modells zeigt eine erfreuliche Übereinstimmung.  

## Schlussfolgerung  

Die Schlussfolgerung adressiert die einleitenden Forderungen an die Thesis. In der Einleitung ist gefordert, eine praxisnahe Methode zur Abbildung des nichtlinearen Tragverhaltens von Stahlbetontragwerken zu entwickeln. Mit der gewählten Abgrenzung, sich auf das Biegetragverhalten zu beschränken, gelingt dies in der Thesis vollumfänglich. Die Modellbildung ist für Ingenieurinnen und Ingenieure in der Praxis zugänglich, da sie vollständig in AxisVM umsetzbar ist. Die angestrebte Präzision der Resultate verdeutlichen die Anwendungsbeispiele, die allesamt zufriedenstellende Ergebnisse liefern.  

Die in der Einleitung kritisierte schwierige Interpretierbarkeit der Resultate anderer Softwarelösungen ist durch die aufgezeigte Modellbildung entschärft. Durch die ausschliessliche Modellierung mit Stäben reduzieren sich die Resultatgrössen auf die Schnittgrössen der Stäbe. Zudem definiert ausschliesslich das Gelenkverhalten das Tragverhalten des Modells. Steifigkeitsabfälle im Tragverhalten lassen sich direkt auf die Gelenkbeziehungen zurückführen.  

Das Gelenkverhalten wird von der Ingenieurin oder dem Ingenieur festgelegt, was eine vollständige Transparenz des Tragverhaltens ermöglicht. Gleichzeitig erfordert dies entsprechendes Fachwissen. Die in der Modellbildung aufgezeigten Gelenkbeziehungen bieten einen Anhaltspunkt, können jedoch beliebig verfeinert werden – stets im Ermessen der Berechnenden.  

Die einfache Modellbildung, die Verantwortung der Gelenkdefinition auf Seiten der Ingenieurin oder des Ingenieurs und die völlige Transparenz des Tragverhaltens führen zu fundierten Aussagen über das Tragverhalten.  

## Ausblick  

Die Thesis zeigt, dass das Tragverhalten der betrachteten Tragwerke mit dem NLFE-Modell gut beschrieben wird. Doch welche Vorteile bietet dieses vertiefte Verständnis des Tragverhaltens?  

Ein besseres Verständnis des Tragverhaltens ermöglicht gezielte Materialeinsparungen. Besonders beim Beton, der aufgrund seiner CO2-Bilanz zu Recht in der Kritik steht, ist der Materialverbrauch eine entscheidende Stellschraube. Werden an den richtigen Stellen Einsparungen erzielt, rechtfertigt dies den zusätzlichen Berechnungsaufwand. Dies mag nicht immer wirtschaftlich sein, ist jedoch im Hinblick auf die Nachhaltigkeit von grosser Bedeutung. Speziell in einer Zeit, in der Nachhaltigkeit im Fokus steht, geniesst dieser Aspekt einen höheren Stellenwert.  

Im Hinblick auf Materialeinsparungen könnten gängige Flachdecken in Zukunft durch ästhetisch ansprechende Kassettendecken ersetzt werden. Werden diese mit der vorgestellten Modellbildung dimensioniert, entstehen optimierte und ingenieurtechnisch anspruchsvolle Bauwerke.  

Gleichzeitig ist auch Kritik an der Modellbildung angebracht. Die Beschränkung auf das Biegetragverhalten erlaubt keine umfassende Optimierung, ohne die Gefahr unberücksichtigter Einflüsse. Insbesondere das ausgeklammerte Querkrafttragverhalten sollte in zukünftigen Arbeiten untersucht werden.


{{< pagebreak >}}

\addchap{Bezeichnungen}

| Variabel                 | Bezeichnung          |
|:----------------------|:------------------|
| $A,B,C$                   | Knotenbezeichnungen|
| $A_s$                   | Querschnittsfläche des Betonstahls |
| $X,Y,Z$                   | Globale Koordinaten               |
| $D_b$                   | Plattensteifigkeit |
| $E$                   | Elastizitätsmodul |
| $E_c$                   | Elastizitätsmodul des Betons |
| $E_{sh}$                   | Verfestigungsmodul des Betonstahls |
| $E_s$                   | Elastizitätsmodul des Betonstahls |
| $EI$                   | Biegesteifigkeit |
| $EI_{I}$                   | Biegesteifigkeit des ungerissenen Querschnitts|
| $EI_{II}$                   | Biegesteifigkeit des gerissenen Querschnitts|
| $F$                   | Kraft               |
| $G$                   | Schubmodul |
| $G_I$                   | Schubmodul des ungerissenen Querschnitts |
| $G_{II}$                   | Schubmodul des gerissenen Querschnitts |
| $I_x$                   | Torsionsträgheitsmoment |
| $I_{Ersatz}$                   | Biegeträgheitsmoment des Ersatzstabs im Stabkreuz |
| $I_{x,Ersatz}$                   | Torsionsträgheitsmoment des Ersatzstabs im Stabkreuz |
| $K$                   | Federsteifigkeit               |
| $M$                   | Biegemoment               |
| $M_x$                   | Im Stabkreuz Biegemoment des Stabs in $X$-Richtung               |
| $M_y$                   | Im Stabkreuz Biegemoment des Stabs in $Y$-Richtung               |
| $M_y$                   | Biegemoment um die lokale $y$-Richtung               |
| $M_z$                   | Biegemoment um die lokale $z$-Richtung               |
| $M_r$                   | Rissbiegemoment |
| $N_x$                   | Normalkraft               |
| $P$                   | Punkt |
| $T$                   | Torsionsmoment               |
| $T_{vert}$                   | Torsionsmoment aus vertikal gerichteten Schubfluss               |
| $T_{horiz}$                   | Torsionsmoment aus horizontal gerichteten Schubfluss               |
| $T_u$                   | Torsionswiderstand               |
| $T_r$                   | Risstorsionsmoment               |
| $T$                   | Torsionsmoment               |
| $T_x$                   | Im Stabkreuz Torsionsmoment des Stabs in $X$-Richtung               |
| $T_y$                   | Im Stabkreuz Torsionsmoment des Stabs in $Y$-Richtung               |
| $V_y$                   | Querkraft in lokaler $y$-Richtung              |
| $V_z$                   | Querkraft in lokaler $z$-Richtung              |
| $a_s$                   | Querschnittsfläche des Betonstahls bezogen auf die Einheitslänge |
| $b$                   | Querschnittsbreite               |
| $c$                   | Betonüberdeckung |
| $d$                   | Statische Höhe |
| $d_v$                   | Hebelarm der inneren Kräfte des Plattenelements              |
| $f_{sy}$                   | Fliessspannung des Betonstahls |
| $f_{su}$                   | Zugfestigkeit des Betonstahls |
| $f_{cc}$                   | Zylinderdruckfestigkeit des Betons |
| $f_{c}$                   | Bauteilfestigkeit des Betons |
| $f_{ct}$                   | Betonzugfestigkeit |
| $h$                   | Querschnittshöhe |
| $h_{eff}$                   | Effektive Höhe des Zugglieds |
| $i_{xy}$                   | Torsionsträgheitsmoment bezogen auf die Einheitslänge |
| $l_{El}$                   | Elementlänge               |
| $l_{Ein}$                   | Einzugslänge               |
| $l_{pl}$                   | Länge des plastischen Gelenks               |
| $m$                   | Biegemoment bezogen auf die Einheitslänge |
| $m_{ij}$                   | Biegemoment in $i$-Richtung auf der $j$-Ebene |
| $n$                   | Wertigkeit               |
| $n_{ij}$                   | Membrankraft bezogen auf die Einheitslänge in $i$-Richtung auf der $j$-Ebene |
| $p$                   | Flächenlast               |
| $q_{ij}$                   | Schubfluss in $i$-Richtung auf der $j$-Ebene|
| $q$                   | Streckenlast               |
| $s_{rm}$                   | Rissabstand |
| $s_{x}$                   | Stabteilung in $x$-Richtung |
| $t$                   | Deckelstärke |
| $u,v,w$                   | Verformung in $x,y,z$-Richtung               |
| $v$                   | Querkraft bezogen auf die Einheitslänge |
| $w_0$                   | Verformung bezogen auf die Elementachse               |
| $x,y,z$                   | Lokale Koordinaten               |
| $x$                   | Laufvariable               |
| $x$                   | Druckzonenhöhe               |
| $z$                   | Hebelarm der inneren Kräfte               |


| Variabel                 | Bezeichnung          |
|:----------------------|:------------------|
| $\alpha, \beta$                   | Winkel |
| $\gamma_z$                   | Schiebung in lokaler $z$-Richtung               |
| $\gamma_y$                   | Schiebung in lokaler $y$-Richtung               |
| $\gamma_{ij}$                   | Schiebung in $i$-Richtung auf der $j$-Ebene               |
| $\delta$                   | Schlupf |
| $\Delta_{\chi}$                   | Krümmungsdifferenz |
| $\varepsilon$                   | Dehnung               |
| $\varepsilon_{cu}$                   | Bruchdehnung des Betons |
| $\varepsilon_{smy}$                   | Entlang des Zugglieds gemittelte Dehnung beim Fliessen |
| $\varepsilon_{smu}$                   | Entlang des Zugglieds gemittelte Dehnung beim Versagen |
| $\varepsilon_{sh}$                   | Dehnung beim Verfestigungsbeginn |
| $\varepsilon_{su}$                   | Dehnung beim Erreichen der Zugfestigkeit |
| $\varepsilon_{q}$                   | Querdehnung |
| $\vartheta$                   | Drillung  |
| $\lambda$                   | Beiwert Zuggurtmodell |
| $\nu$                   | Querdehnzahl |
| $\rho$                   | Geometrischer Bewehrungsgehalt |
| $\rho_x$                   | Geometrischer Bewehrungsgehalt in $x$-Richtung |
| $\rho_y$                   | Geometrischer Bewehrungsgehalt in $y$-Richtung |
| $\sigma$                   | Normalspannung |
| $\sigma_c$                   | Normalspannung des Betons |
| $\sigma_s$                   | Normalspannung des Betonstahls |
| $\tau$                   | Schubspannung |
| $\tau_{ij}$                   | Schubspannung in $i$-Richtung auf der $j$-Ebene |
| $\varphi$                   | Verdrehung, Rotation               |
| $\varphi_R$                   | Relative Gelenkrotation               |
| $\varphi_{ri}$                   | Einzelne Rissrotationen |
| $\varphi_{adm}$                   | Rotationsvermögen, zulässige Rotation |
| $\chi_{ij}$                   | Krümmung in $i$-Richtung auf der $j$-Ebene |
| $\chi_{cu}$                   | Bruchkrümmung begrenzt durch Betonversagen |
| $\chi_{su}$                   | Bruchkrümmung begrenzt durch Betonstahlversagen |
| $\chi_{r}$                   | Krümmung beim Reissen des Querschnitts |
| $\chi_{y}$                   | Krümmung beim Fliessen der Bewehrung |
| $\chi_y$                   | Krümmung um die lokale $y$-Richtung               |
| $\chi_z$                   | Krümmung um die lokale $z$-Richtung               |

| Variabel                 | Bezeichnung          |
|:----------------------|:------------------|
| $\oslash$                   | Durchmesser Bewehrungsstahl |

