project:
  type: book

language:
  section-title-appendices: "Anhang"

book:
  title: Tragverhalten von Stahlbetontragwerken
  subtitle: Modellvorstellungen zur nichtlinearen Verformungsberechnung
  author: Pascal Gitz
  date: 2025.01.17
  date-format: full
  chapters:
    - index.qmd
    - 04_Einfuehrung.qmd
    - references.qmd

  appendices: 
    - A1_Traegerrost_Marti.ipynb
    - A2_Zweifeldtraeger_Jaeger.ipynb

bibliography: references.bib

format:
  pdf:
    # pdf-engine: latexmk
  # Titelblatt und Kurzfassung
    template-partials:
      - ../config/style/title.tex
    include-in-header: 
      - text: |
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
      - file: ../config/style/styling_nach_hslu.sty

    include-before-body:
      - file: 01_redlichkeitserklaerung.tex
      - file: 02_kurzfassung.tex
      - text: |
          \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
            showspaces = false,
            showtabs = false,
            breaksymbolleft={},
            breaklines
            % Note: setting commandchars=\\\{\} here will cause an error 
          }



  # Dokument
    documentclass: scrreprt
    toc-depth: 2
    lof: true
    # lot: true
    lang: de
    # keep-tex: true

  # Figuren
    fig-pos: 'H'
    fig-format: svg
  
  # Verlinkungen
    csl: ../config/style/diabetologia.csl
    link-citations: True
    linkcolor: Black
  
  # Tabellen
    tbl-colwidths: [50,50]
    
  # Code
    execute:
      echo: false
      warning: false
    highlight-style: kate
    code-block-bg: "#F5F5F5"
    code-block-border-left: false
    code-line-numbers: false
  
  # Font
    # fontfamily: TeX Gyre Pagella
    mainfont: TeX Gyre Pagella
    # sansfont: TeX Gyre Pagella
    fontsize: 11pt
    

  docx:
    lang: de
    fig-format: svg
    csl: ../config/style/diabetologia.csl
    link-citations: true
    tbl-colwidths: [50,50]
    echo: false
    warning: false



  # html:
  #   fig-format: svg
  #   lang: de
  #   csl: diabetologia.csl
  #   link-citations: True
  #   tbl-colwidths: [50,50]

